### ISSUE TITLE
npm start fails on newest master build

### ISSUE THREAD

**Issue by paanvaannd** [blahsd/snwe#15]
```
$ git clone https://github.com/blahs.snwe && \
cd snwe && \
rm app/css/colors.wal.css && \
npm start
```
fails since commit 204b461 with an error similar to electron/electron-quick-start#108 with the following quoted portion being able to fix the issue on my end:

> If that file is missing your node_modules install probably glitched out, it happens sometimes. Just delete your node_modules folder and re run `npm install`

The debug branch does not have this issue.

**Comment by blahsd** [comment]
Fixed
