### ISSUE TITLE
Electron Content Security Policy warning upon summoning the preferences window

### ISSUE THREAD

**Issue by paanvaannd** [blahsd/snwe#16]
The following message is displayed when running snwe and opening the preferences window:

> Electron Security Warning (Insecure Content-Security-Policy) font-weight: bold; This renderer process has either no Content Security Policy set or a policy with "unsafe-eval" enabled. This exposes users of this app to unnecessary security risks.
>
> For more information and help, consult https://electronjs.org/docs/tutorial/security.
This warning will not show up once the app is packaged.

**Comment by blahsd** [comment]
Fixed
