### ISSUE TITLE
`npm start` generates large non-transparent electron window with debugging tools and error message in terminal

### ISSUE THREAD

**Issue by paanvaannd** [blahsd/snwe#2]
<img width="2560" alt="error" src="https://user-images.githubusercontent.com/16567134/39761108-3141a132-52a5-11e8-8785-3eec24f2cd56.png">

*Note: the purple rectangle is a window border drawn by chunkwm around the Grab.app GUI; disregard that.*

This window is spawned upon starting snwe. It takes up a good portion of the screen (~80%?) without being resized through chunkwm. In the above image, the spawned window is fullscreen because of chunkwm.

On the bottom-right, in the debugging panes, there are some properties that are striked out. Mousing over those values shows a tooltip saying "Invalid property values."

Furthermore, the following is the terminal output upon running `npm start` in the cloned repo:

```
$ npm start

> snwe@0.1.0 start /Users/pavananand/bin/snwe
> electron .

2018-05-08 09:51:38.353 Electron[11582:51534] *** WARNING: Textured window <AtomNSWindow: 0x7feaccd49120> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

**Comment by blahsd** [comment]
I am so happy to see you here so quickly! I owe you one. You were getting the devTools showing up. The latest commit should get rid of that and also of chunkwm's purple rectangle. 

I'm not sure what the warning is. I'm getting it too, but can't find a conclusive answer on how to remove it.

**Comment by paanvaannd** [comment]
The NSWindow error appears to be an Electron issue, so it will have to be fixed upstream, I believe: https://github.com/electron/electron/issues/12814
