### ISSUE TITLE
Error while npm install on osx

### ISSUE THREAD

**Issue by karambaq** [blahsd/snwe#35]
> electron@2.0.3 postinstall /Users/pq/snwe/node_modules/electron
> node install.js

> electron-prebuilt@1.4.13 postinstall /Users/pq/snwe/node_modules/electron-prebuilt
> node install.js

> snwe@0.1.0-rc.2 postinstall /Users/pq/snwe
> install-app-deps

    sh: install-app-deps: command not found
    npm ERR! file sh
    npm ERR! code ELIFECYCLE
    npm ERR! errno ENOENT
    npm ERR! syscall spawn
    npm ERR! snwe@0.1.0-rc.2 postinstall: `install-app-deps`
    npm ERR! spawn ENOENT
    npm ERR!
    npm ERR! Failed at the snwe@0.1.0-rc.2 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/pq/.npm/_logs/2018-06-22T20_20_00_727Z-debug.log`

**Comment by blahsd** [comment]
Did you run `npm install`?

**Comment by mdomke** [comment]
I'm having the same problem. I'm running `npm install` in a freshly cloned repo
```sh
λ npm install

> snwe@0.1.0-rc.2 postinstall /Users/mdomke/Source/other/snwe
> install-app-deps

sh: install-app-deps: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! snwe@0.1.0-rc.2 postinstall: `install-app-deps`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the snwe@0.1.0-rc.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mdomke/.npm/_logs/2018-06-22T21_18_11_309Z-debug.log
```

**Comment by karambaq** [comment]
@blahsd Yes

**Comment by georgenica** [comment]
@blahsd same problem here. although, as per @mdomke , you can indeed run the app with `npm start`.

**Comment by blahsd** [comment]
Please try the fix! Be sure to be on branch `iss35`. If someone can confirm that this fixes the issue for them, I'll merge into `master`.

Thank you all for signalling, btw.

**Comment by karambaq** [comment]
@blahsd Didn't work for me on the iss35

**Comment by blahsd** [comment]
@karambaq are you getting the same error? In that case it’s super weird because I removed the post install script altogether (it was actually a leftover of a previous version and no longer needed). The postinstall command call install-app-deps, so without it, that shouldn’t pop up anywhere

**Comment by karambaq** [comment]
my bad, now it works on iss35
