### ISSUE TITLE
How can I apply that theme?

### ISSUE THREAD

**Issue by karambaq** [blahsd/snwe#36]
https://github.com/blahsd/snwe/blob/iss35/demo/theme4.png

**Comment by blahsd** [comment]
Ah, shit. I had forgotten about that theme. I disabled it when I implemented the new window-management framework, but then I forgot to get back to it to make it work again. I will page you when it's up (1-2 days). Thanks for letting me know

**Comment by blahsd** [comment]
Good to go @karambaq! Thanks for the patience
