### ISSUE TITLE
Really stupid question but how do you start it

### ISSUE THREAD

**Issue by nihal127** [blahsd/snwe#37]
How do you start the prebuilt binary? I can't find any app or anything to drag into Applications, just the actual icons.

**Comment by blahsd** [comment]
Well I thought what the hell, I'll download my own executable and do a step by step guide and nothing, it's broken as shit. Turns out it was only working on my system because of a series of coincidences. Jesus.

**Comment by blahsd** [comment]
All should be fixed in the latest commit. Compiled release soon to come.

**Comment by blahsd** [comment]
Compiled published!
