### ISSUE TITLE
Not able to change the command tabs 

### ISSUE THREAD

**Issue by msulli888** [blahsd/snwe#40]
I keep trying to change the command tabs on the bar. I have added .command files under the `command-wrappers` folder and changed config.json to match, however the config file keeps updating and overwriting my changes. How can I sort this?

**Comment by blahsd** [comment]
You shouldn’t add the command files, snwe  will make them on its own. You only need to edit config.json. So first thing I recommend is, nuke your ../Application\ Support/snwe folder, then try modifying just the config.json. If it still doesn’t work, post here both config and output, if you’re getting any

**Comment by blahsd** [comment]
Did it work for you?

**Comment by msulli888** [comment]
Sorry forgot to reply. Yes it seems to have worked.

**Comment by blahsd** [comment]
No worries, glad it worked out!
